// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABqJTp-8kiknk3OmOCqwkgLM4aTiI3-eg',
    appId: '1:124401600750:web:23f552ef0e5d95b066cbff',
    messagingSenderId: '124401600750',
    projectId: 'saqr-s-project',
    authDomain: 'saqr-s-project.firebaseapp.com',
    storageBucket: 'saqr-s-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIme6rHAvxaWtK4C42yDCtjqpS0LJi5dg',
    appId: '1:124401600750:android:5c7f1f387eaaa81466cbff',
    messagingSenderId: '124401600750',
    projectId: 'saqr-s-project',
    storageBucket: 'saqr-s-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGOAbTg_5al8UaNEqfywFNgs7Z_s90tOM',
    appId: '1:124401600750:ios:03a313a821a5f76766cbff',
    messagingSenderId: '124401600750',
    projectId: 'saqr-s-project',
    storageBucket: 'saqr-s-project.firebasestorage.app',
    iosBundleId: 'com.example.hourFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGOAbTg_5al8UaNEqfywFNgs7Z_s90tOM',
    appId: '1:124401600750:ios:03a313a821a5f76766cbff',
    messagingSenderId: '124401600750',
    projectId: 'saqr-s-project',
    storageBucket: 'saqr-s-project.firebasestorage.app',
    iosBundleId: 'com.example.hourFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABqJTp-8kiknk3OmOCqwkgLM4aTiI3-eg',
    appId: '1:124401600750:web:65c5c74206d7908c66cbff',
    messagingSenderId: '124401600750',
    projectId: 'saqr-s-project',
    authDomain: 'saqr-s-project.firebaseapp.com',
    storageBucket: 'saqr-s-project.firebasestorage.app',
  );
}
